# Generated by Django 5.2.7 on 2025-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('property_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'For Sale')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('flat', 'Flat'), ('villa', 'Villa')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_built', models.PositiveIntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('property_description', models.TextField()),
                ('Features_and_amenities', models.TextField()),
                ('rent_duration', models.CharField(blank=True, choices=[('month', 'Per Month'), ('year', 'Per Year')], max_length=10, null=True)),
            ],
        ),
    ]
