# Generated by Django 5.2.7 on 2025-10-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RukApp', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
    ]
