# Generated by Django 5.2.7 on 2025-10-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RukApp', '0003_rename_name_property_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='RukApp.address'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_PropertyImage',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='RukApp.property')),
            ],
        ),
    ]
